INSERT INTO Room (svgRef,mapId,name) VALUES
    (1,1,'Main reception'),
    (2,1,'Library'),
    (3,1,'Lecture hall'),
    (4,1,'Main hall'),
    (5,1,'Kitchen'),
    (6,1,'Backstage'),
    (7,1,'Props'),
    (8,1,'Dressing room 1'),
    (9,1,'Dressing room 2'),
    (10,1,'Student disabled toilets'),
    (11,1,'Student female toilets'),
    (12,1,'Student male toilets'),
    (13,1,'Visitor disabled toilets'),
    (14,1,'Visitor female toilets'),
    (15,1,'Visitor male toilets'),
    (16,1,'Medical room'),
    (17,1,'Staff corridor'),
    (18,1,'Admin office 1'),
    (19,1,'Admin office 2'),
    (20,1,'IT office'),
    (21,1,'Server room'),
    (22,1,'Admin office'),
    (23,1,'Staff break room'),
    (24,1,'Head\'s office'),
    (25,1,'Staff disabled toilets'),
    (26,1,'Staff female toilets'),
    (27,1,'Staff male toilets'),
    (28,1,'Humanities corridor'),
    (29,1,'Humanities office'),
    (30,1,'Languages classroom'),
    (31,1,'History classroom'),
    (32,1,'Geography classroom'),
    (33,1,'Religious classroom'),
    (34,1,'Maths and English corridor'),
    (35,1,'English office'),
    (36,1,'English classroom 1'),
    (37,1,'English classroom 2'),
    (38,1,'English classroom 3'),
    (39,1,'English classroom 4'),
    (40,1,'Maths office'),
    (41,1,'Maths classroom 1'),
    (42,1,'Maths classroom 2'),
    (43,1,'Maths classroom 3'),
    (44,1,'Maths classroom 4'),
    (45,1,'Sciences and Arts corridor'),
    (46,1,'Boiler room'),
    (47,1,'Sciences office'),
    (48,1,'IT classroom'),
    (49,1,'Computing classroom'),
    (50,1,'Business classroom'),
    (51,1,'Chemistry classroom'),
    (52,1,'Physics classroom'),
    (53,1,'Biology classroom'),
    (54,1,'Music classroom'),
    (55,1,'Drama classroom'),
    (56,1,'Art classroom');
UPDATE ROOM SET isSpawnpoint=1 WHERE mapId=1 AND svgRef=1;
INSERT INTO Door (mapId,svgRef1,svgRef2) VALUES
    (2,1,2),
    (2,1,3),
    (2,1,4),
    (2,1,10),
    (2,1,11),
    (2,1,12),
    (2,1,13),
    (2,1,14),
    (2,1,15),
    (2,1,16),
    (2,1,28),
    (2,1,34),
    (2,1,45),
    (2,2,35),
    (2,4,5),
    (2,4,6),
    (2,4,23),
    (2,6,7),
    (2,6,17),
    (2,7,8),
    (2,7,9),
    (2,7,54),
    (2,7,55),
    (2,17,18),
    (2,17,19),
    (2,17,20),
    (2,17,21),
    (2,17,22),
    (2,17,23),
    (2,17,24),
    (2,17,25),
    (2,17,26),
    (2,17,27),
    (2,20,48),
    (2,21,49),
    (2,28,29),
    (2,28,30),
    (2,28,31),
    (2,28,32),
    (2,28,33),
    (2,34,35),
    (2,34,36),
    (2,34,37),
    (2,34,38),
    (2,34,39),
    (2,34,40),
    (2,34,41),
    (2,34,42),
    (2,34,43),
    (2,34,44),
    (2,36,37),
    (2,38,39),
    (2,41,42),
    (2,43,44),
    (2,45,46),
    (2,45,47),
    (2,45,48),
    (2,45,49),
    (2,45,50),
    (2,45,51),
    (2,45,52),
    (2,45,53),
    (2,45,54),
    (2,45,55),
    (2,45,56),
    (2,48,49),
    (2,51,52),
    (2,52,53),
    (2,54,55);
INSERT INTO Topic (name) VALUES ('Placeholder');
INSERT INTO Definition (topicId,definition,difficulty,answerRegex,usageTemplate,wordClass) VALUES
    (1,'Malware which causes seemingly unremovable advertisements to display',5,'adware','I\'ve been infected by some {answer} and now I can\'t stop seeing ads on my computer','noun'),
    (1,'Performs maths in the CPU',4,'alu|arithmetic logic unit','My CPU\'s {answer} can add numbers together, but it can\'t square root them','noun'),
    (1,'Translates the human form of machine code into binary',7,'assemblers?','I\'m going to pass my code through an {answer} so I can execute it','noun'),
    (1,'Human form of machine code',7,'assembly','I\'m writing some code using {answer}','noun'),
    (1,'The base 2 numbering system used by computers',3,'bin(ary)?','158 in {answer} is 10011110','noun'),
    (1,'Searching algorithm where you split the middle of sorted data',6,'binary ?(search(ing)?)?','I could use a {answer} search to find which player on the leaderboard has 20 points','noun/verb'),
    (1,'First code run when the system turns on which manages hardware and starts the operating system',7,'bios|basic (input/?output|i/?o) system|uefi|unified extensible firmware interface|post|power(-| )on self(-| )test','I\'ve turned on my computer but I need to wait for the {answer} before I can log in','noun'),
    (1,'A single binary digit',1,'bit','I could store an array of booleans using a bunch of {answer}s to improve memory efficiency','noun'),
    (1,'Datatype which represents either true or false',6,'bool(ean)?','I could store whether or not you\'ve answered this question yet using a {answer}','adjective/noun'),
    (1,'Sorting algorithm where you go from start to finish comparing each value to the next',6,'bubble ?(sort(ing)?)?','I\'m going to sort this list using a {answer}','noun/verb'),
    (1,'Topology where every device is connected through a single wire',6,'bus','I\'ve connected the computers in my house using a {answer} topology','noun'),
    (1,'Eight binary digits',1,'bytes?','ASCII stores every character using a single {answer}','noun'),
    (1,'Volatile memory which stores current data, frequent addresses and operations inside the CPU',5,'(cpu )?cache( memory)?','My CPU has more {answer} so it can efficiently run more programs','noun/verb'),
    (1,'Datatype for individual letters, numbers, symbols etc',5,'char(acter)?s?','I want to iterate over each {answer} in this string','noun'),
    (1,'Translates high level code to machine code all at once',7,'compilers?','My code looks inefficient but it\'s more readable and the {answer} will optimize it','noun'),
    (1,'Multiple clocks which can be inside the CPU at the same time',5,'cores?','My CPU has 4 {answer} making it decent at multi-tasking','noun'),
    (1,'Brain of the computer',1,'cpu|central processing unit','My games are laggy and I think the {answer} is the bottleneck so I\'m going to upgrade it','noun'),
    (1,'Controls flow of data in the CPU',6,'cu|control units?',NULL,'noun'),
    (1,'Routes data take on the between parts of the motherboard (e.g: from CPU to RAM)',6,'(data )?bus(es)?','The CPU and RAM are seated close to each other so that the {answer} can be shorter','noun'),
    (1,'Trying to remove issues in a program',6,'debug(g?ing)?','I\'m not sure why my code is not working so I need to {answer} it','verb'),
    (1,'The base 10 numbering system most commonly used by humans',3,'den(ary)?|dec(a|imal)?','The first 10 even {answer} numbers are 2, 4, 6, 8, 10, 12, 14, 16, 18 and 20','noun'),
    (1,'Making data unusable to interceptors',6,'encrypt(ion|ing)?','I\'m going to {answer} the file before I send it to you because I don\'t want anybody else to see it','noun/verb'),
    (1,'Wire used to connect devices in a network',6,'ethernet( cables?)?','I\'ve just moved my computer further away from the router so now I need a longer {answer}','noun'),
    (1,'Moving part to reduce the temperature of components',2,'(cpu )?fans?','Whenever I\'m playing games, I notice my {answer} becomes louder','noun'),
    (1,'Network firmware which analyzes packets and blocks potentially malicious ones before they can pass',5,'firewalls?','I don\'t want my son playing games at night so I\'m going to create a {answer} rule which blocks games after 9PM','noun'),
    (1,'Datatype for a number which may have a decimal point',7,'real((-| )number)?|float(ing(-| )point(-| )(integer|number)?)?','If I stored your number of points as a {answer}, you could have 4.13 points','noun'),
    (1,'Python keyword for iterating through all items in a list',7,'for','{answer} i in range(5):','keyword'),
    (1,'Algorithm followed for sending files over a network',7,'ftp|file transfer protocol','I have an {answer} server to share some of my files with people','noun'),
    (1,'Block of code which calculates a value to return to the code which executed it',7,'function','My addIconTo {answer} returns the created icon','noun'),
    (1,'1000 megabytes',1,'(1 )?(gb|giga((-| )byte)?)','My phone has 128 {answer}s of storage','noun'),
    (1,'Part responsible for rendering on modern systems',4,'gpu|graphic((al|s)? processing unit|s? card)','I\'m going to buy a {answer} so I can play more realistic-looking games','noun'),
    (1,'The base 16 numbering system often used for colors',5,'hex(a(decimal)?)?','158 in {answer} is 9E','noun'),
    (1,'Programming languages which are designed to be easily understood by humans but must be translated to be used by a computer',6,'high((-| )level(( programming)?(-| )languages?)?)?','I\'m using a {answer} programming language to keep it maintainable','noun'),
    (1,'The language used for describing a websites structure',7,'html|hyper ?text markup language','"Inspect Element" allows you to view and modify the {answer} of this website','noun'),
    (1,'Unsecure algorithm used between a web server and client',7,'http|hyper ?text transfer protocol','If you used {answer} to request this website, I would use {answer} to tell you to use {answer}S instead','noun'),
    (1,'Secure algorithm used between a web server and client',7,'http(s| secure)|hyper ?text transfer protocol secure','You used {answer} to request this website and I used {answer} to send it to you','noun'),
    (1,'Broadcasts data to all devices on a network',6,'hubs?','You might have a {answer} in your house, but you probably have a switch instead','noun'),
    (1,'Text-editor like software which aids a programmer to code',6,'(ide|integrated development environment)s?','My favourite {answer} is Visual Studio Code because it has a lot of useful extensions','noun'),
    (1,'Algorithm used for downloading email from a server to be stored only on the device',7,'imap|internet message access protocol','I\'ve setup my own {answer} server so that another entity doesn\'t have access to my emails','noun'),
    (1,'Sorting algorithm where you add each element into a new list one at a time',7,'insert(ion)?( sort(ing)?)?','My list isn\'t going to be very big so I\'m going to use a {answer} to keep it simple','noun/verb'),
    (1,'Datatype for a number without a decimal point',4,'int(eger)?s?','Your number of points are stored as an {answer}','noun'),
    (1,'Translates high level code to machine code line-by-line',7,'interpreters?','Python uses an {answer} meaning you need to have it installed to run Python code','noun'),
    (1,'Algorithm followed for sending data over the public internet with packets',6,'ip|tcp|(internet|transmission control) protocol','Most online data is sent using a form of {answer}','noun'),
    (1,'Block of code run multiple times until a condition is met',7,'iterat(e|ion|ing)|while( loop)?','I could {answer} over all the rooms on the map to identify which rooms you can move to','noun/verb'),
    (1,'Common file type for lossly compressed images',6,'\\.?jpe?g','My SD card is quite small so my camera stores my photos as a {answer}, but this means the photos lose some of their quality','noun'),
    (1,'8000 binary digits, 1000 bytes',3,'(1 )?(kb|kilo(-| )?byte)','The Gameboy only had 64 {answer} of on-board storage','noun'),
    (1,'Network which uses a small physical area',6,'lan|local area network','I\'m going to host a {answer} party so me and my friends can hang out and play multiplayer games together','noun'),
    (1,'Searching algorithm where you check each item in a list one at a time in the order given',6,'linear(ly)?( search(ing)?)?','My data isn\'t sorted at all so I\'m just going to use a {answer} search','noun/verb'),
    (1,'Datatype containing multiple items in an index',5,'list|array','I have an {answer} of all the players in this game','noun'),
    (1,'Programming languages which are difficult for a human to understand but easily understood by a computer',6,'low((-| )level(( programming)?(-| )languages?)?)?','Performance is of upmost priority for my program so I\'m going to use a {answer}','noun'),
    (1,'Hexadecimal identifier for devices on a network',8,'(mac|media access control)( address)?','A switch uses a device\'s {answer} to identify it','noun'),
    (1,'Code written in pure binary',7,'machine(-| )code','An assembler translates assembly into {answer}','noun'),
    (1,'Catch-all term for any software you\'re likely to not want installed',1,'mal(ious soft)?ware','Pirated games often contain {answer}','noun'),
    (1,'Register storing the address currently being accessed',6,'mar|memory address register','Every clock cycle, the contents of the program counter are copied to the {answer}','noun'),
    (1,'A structural computer language such as HTML which uses angle brackets (<>) for opening and closing tags',8,'markup( language)?s?|xml','SVG and MathML are both {answer}s','noun'),
    (1,'Register storing data received from RAM',6,'mdr|memory data register','An LDA instruction will ask the RAM for data which will be stored in the {answer}','noun'),
    (1,'1000 kilobytes',3,'(1 )?(mb|mega((-| )?byte)?)','The Wii only had 512 {answer} of internal storage','noun'),
    (1,'A divide and conquer sorting algorithm',6,'(merge|quick)( sort(ing)?)?',NULL,'noun/verb'),
    (1,'Topology where all devices are directly connected to each other',6,'mesh','My network is mission-critical so I\'m using a {answer} network for extra redundancy','noun'),
    (1,'Block of code which is executed but does not return a value to the code which executed it',6,'methods?',NULL,'noun'),
    (1,'Connects a LAN to a WAN using telephone lines',6,'modems?',NULL,'noun'),
    (1,'Skeleton of the computer',5,'(pc )?case|mother(-| )?board','The CPU is installed to the {answer}','noun'),
    (1,'Common file type for lossly compressed audio',4,'\\.?mp3|mpeg(-| )?3',NULL,'noun'),
    (1,'Common file type for lossly compressed video',4,'\\.?mp4|mpeg(-| )?4',NULL,'noun'),
    (1,'Four binary digits',3,'nibble','A single hexadecimal digit is equivalent to a single {answer}','noun'),
    (1,'Connects a computer to a LAN',6,'nic|network( interface)? card','My motherboard doesn\'t have networking built-in, so I installed a {answer}','noun'),
    (1,'Memory which stores data even when power is off',5,'non(-| )volatile( memory)?',NULL,'adjective/noun'),
    (1,'Software where the code is publicly viewable and usually in the public domain',6,'oss|open(-| )?source( software)?','Lots of {answer} software is hosted on GitHub','noun'),
    (1,'The subject/quantity of a calculation',8,'operand','In 1+1, 1 is the {answer}','noun'),
    (1,'The type or symbol used in a calculation',8,'operat(or|ion)','In 1+1, + is the {answer}','noun'),
    (1,'Software which connects other software to hardware and provides I/O',6,'os|operating systems?','I use Windows 10 as my {answer}','noun'),
    (1,'Network data which has been split into chunks',7,'(data )?packets?','I use a {answer} sniffer to see the network traffic entering and leaving my computer','noun'),
    (1,'Register storing the next address for the FEC',6,'pc|program counter','In order to execute this function, I\'m going to store the address of the function in the {answer}','noun'),
    (1,'Common file type for printer-ready documents',6,'\\.?pdf|portable document format',NULL,'noun'),
    (1,'1000 terabytes',4,'pb|peta(-| )?bytes?','There is not currently a commercially available storage device which with a {answer} storage capacity, but many companies store many {answer}s of data every day','noun'),
    (1,'Common file type for losslessly compressed images',4,'\\.?png|portable network graphics?',NULL,'noun'),
    (1,'Algorithm used for viewing mail stored only on the server',6,'pop3?|post(-| )office protocol( 3)?',NULL,'noun'),
    (1,'Common function (name used by Python) for outputting messages',4,'print(ing)?','{answer}("Hello, world!")','noun/verb'),
    (1,'Software made by a business which must be licensed to view and edit',7,'(proprietary|closed(-| )?source)( software)?','Most games on Steam are {answer}, but some members of the modding community dedicate themselves to reverse-engineering them','noun'),
    (1,'The name given to code written for planning and not to be executable',5,'pseudo((-| )?code)?','I don\'t know this programming language, but I can still write {answer} for what I need done in it','noun'),
    (1,'Provides power to all the other components',5,'psu|power(-| )supply( unit)?','I have a powerful GPU so I need a {answer} with a high wattage','noun'),
    (1,'Short term memory',2,'ram|primary storage|(volatile|random( access|ly accessed)) memory','How much {answer} does your computer have?','noun'),
    (1,'Software which disallows access to your computer or files until you pay a fee',6,'ransom(-| )?ware','Wannacry is an infamous {answer} which affected organizations such as the NHS','noun'),
    (1,'Topology where every device is directly connected to 2 other devices',6,'ring','Every device in my house needs to be connected but I want to use as little cable as possible so I\'ll use a {answer} network','noun'),
    (1,'Stores the BIOS',6,'rom|read(-| )only memory','Data stored in {answer} can not be updated','noun'),
    (1,'Software which allows someone else to access your computer and use it however they like',9,'rats?|remote(-| )access trojans?|rootkits?','Strange things have been happening on my computer so I think someone has a {answer} on it','noun'),
    (1,'Connects multiple subnetworks into one larger network',6,'routers?','I have a network device which actually takes on a lot of roles, but I usually just call it the {answer}','noun'),
    (1,'Long term memory',5,'secondary storage|hdd|ssd|(hard((-| )disk)?|solid(-| )state)((-| )drives)?','I\'ve nearly filled my {answer} with all my games, I\'ll need to buy some more','noun'),
    (1,'Block of code only run if a condition is met',7,'selection|if( (statement|block))?','{answer} correct:','noun'),
    (1,'Stores data to allow other devices on a network to access including websites',6,'servers?','I have a {answer} for this storing some files, hosting this website and for my database','noun'),
    (1,'Generic algorithm used for sending/receiving mail over a network',7,'smtp|simple mail transfer protocol',NULL,'noun'),
    (1,'Software which sends user data elsewhere without your knowledge',6,'spyware','Many people argue that popular apps such as Google and TikTok are effectively {answer}','noun'),
    (1,'Topology where every device connects through a server',6,'star','To cut costs on individual machines, all software is installed on a server and a {answer} network is used to connect the computers to it','noun'),
    (1,'Datatype which contains a list of letters, numbers or symbols to form a word or sentence',5,'str(ing)?s?','Your answer is a {answer}','noun'),
    (1,'Any block of code, regardless of whether it returns a value, which can be executed from elsewhere in the program',8,'sub-?routine','In Scratch, {answer}s are known as "custom hat blocks"','noun'),
    (1,'Targets data to a specific device on a network',6,'switch','{answer}es are considered by many to be more modern alternative to hubs','noun'),
    (1,'The \'grammar\' of code',5,'syntax','I missed a bracket so I got a {answer} error','noun'),
    (1,'1000 gigabytes',4,'tb|tera((-| )?byte)?','Most new gaming computers come with about 1 {answer} of storage','noun'),
    (1,'Layout of a network',6,'(network )?topology','My house uses a star {answer}','noun'),
    (1,'Malware which disguises itself as legitimate software',6,'trojan( horse)?s?','Pirated games such as Terraria are often a {answer} and trick certain silly users into running them as administrator','noun'),
    (1,'Term used when converting between datatypes',7,'type(-| )?cast(ing)?','User input is a string, but I only want integers so I need to {answer} their input','verb'),
    (1,'Algorithm followed for sending data over the public internet without packets',9,'udp|user datagram protocol','Many competitive games use {answer} because it has a low latency','noun'),
    (1,'Data allocated to a program which can be changed',5,'var(iable)?s?','Your answer is stored in a {answer} and changes to that variable are replicated here --> {answer}','adjective/noun'),
    (1,'Memory which stops storing data when power is turned off',5,'volatile( memory)?','RAM is {answer} which is why you need to save your documents before turning off your computer','adjective/noun'),
    (1,'Network which uses a large physical area',6,'wan|wide(-| )area network','The internet is the largest {answer}','noun'),
    (1,'Network-side device for Wi-Fi connections',6,'wap|wireless access point',NULL,'noun'),
    (1,'Common file type for losslessly compressed audio',6,'\\.?wav',NULL,'noun'),
    (1,'Python keyword for iterating until a condition is no longer met',6,'while','{answer} not answered_correctly:','keyword'),
    (1,'Connects devices to a network wirelessly',4,'wi-?fi','What\'s the {answer} password?','noun'),
    (1,'Malware which spreads itself through networking and external drives',6,'worms?|virus(es)?','A device on my network has been infected with a {answer} so I\'ve disconnected my internet to quarantine it.','noun');
INSERT INTO ShopItem (name,description,cost,`action`) VALUES
    ('Wormhole (random teleport)','You\'re doing some physics work and you manage to create a wormhole! You get teleported to a random room.',3,'randomTeleport'),
    ('Class swap','After misbehaving in the lesson, your teacher decides to exchange you with a student from another class so you swap rooms with another player',7,'swapRandPlayer'),
    ('Encourage good deed','You encourage another student to donate to charity. A random player will lose 5 points!',7,'subtractRandPlayerPoints/5'),
    ('Report stolen property','You report to your teacher that 5 points in the school have went missing, so your school replaces them. 5 rooms are unclaimed!',3,'unclaimAbsoluteRooms/5'),
    ('Report school heist','You report to your teacher that a number of points have been stolen around the school, so your school replaces them. 50% of rooms are unclaimed!',7,'unclaimPercentageRooms/50');