-- CreateTable
CREATE TABLE `Room` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `map_id` INTEGER UNSIGNED NOT NULL,
    `name` VARCHAR(191) NULL,

    PRIMARY KEY (`id`, `map_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Room` ADD CONSTRAINT `Room_map_id_fkey` FOREIGN KEY (`map_id`) REFERENCES `Map`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
