ALTER TABLE `Door` DROP FOREIGN KEY `Door_mapId_room1Id_fkey`;
ALTER TABLE `Door` DROP FOREIGN KEY `Door_mapId_room2Id_fkey`;

ALTER TABLE `Door` DROP PRIMARY KEY,
    CHANGE COLUMN `room1Id` `svgRef1Id` INTEGER UNSIGNED NOT NULL,
    CHANGE COLUMN `room2Id` `svgRef2Id` INTEGER UNSIGNED NOT NULL,
    ADD COLUMN `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    ADD PRIMARY KEY (`id`);

ALTER TABLE `Room` DROP PRIMARY KEY,
    CHANGE COLUMN `id` `svgRef` INTEGER UNSIGNED NOT NULL,
    ADD COLUMN `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    ADD PRIMARY KEY (`id`);

CREATE UNIQUE INDEX `Room_mapId_svgRef_key` ON `Room`(`mapId`, `svgRef`);
CREATE UNIQUE INDEX `Door_mapId_svgRef1Id_svgRef2Id_key` ON `Door`(`mapId`, `svgRef1Id`, `svgRef2Id`);
ALTER TABLE `Door` ADD CONSTRAINT `Door_mapId_svgRef1Id_fkey` FOREIGN KEY (`mapId`, `svgRef1Id`) REFERENCES `Room`(`mapId`, `svgRef`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT `Door_mapId_svgRef2Id_fkey` FOREIGN KEY (`mapId`, `svgRef2Id`) REFERENCES `Room`(`mapId`, `svgRef`) ON DELETE RESTRICT ON UPDATE CASCADE;
