name: Testing

on:
  push:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: npm run test:unit
  integration-test:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 60
    env:
      PUBLIC_GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
      ALLOWED_DOMAIN: example.com
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: bunx playwright install --with-deps
      - run: bun run test:integration
